name: Autoupdate branch

# **What it does**: The next pull request in the merge queue will get its
# branch updated with main. Only updating one branch ensures that pull requests
# in the queue are merged sequentially.
# **Why we have it**: So we don't have to watch pull requests and click
# update branch 1000x.
# **Who does it impact**: Our health.
#
# The merge queue consists of any pull requests with automerge enabled and
# are mergeable. There is a label that can be used to skip to the front of
# the queue (`skip-to-front-of-merge-queue`).
#
# This workflow is triggered when a `push` event occurs ON the `main` branch
#  (e.g. a PR was merged or a force-push was done).
#
# This workflow runs on all PRs created from source branches within the
# public and private docs repos but is won't work for PRs created from
# forked repos.
#

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update next PR in queue
        env:
          GITHUB_TOKEN: ${{ secrets.DOCUBOT_REPO_PAT }}
        run: node .github/actions-scripts/update-merge-queue-branch.js
