name: Lint JS

# **What it does**: Lints our JavaScript to ensure the code matches the specified code style.
# **Why we have it**: We want some level of consistency to our JavaScript.
# **Who does it impact**: Docs engineering, open-source engineering contributors.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.ts'
      - '**.tsx'
      # In case something like eslint or tsc or prettier upgrades
      - 'package-lock.json'
      # Ultimately, for debugging this workflow itself
      - .github/workflows/js-lint.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run TypeScript
        run: npm run tsc
