name: OpenAPI dev mode check

# **What it does**: Checks that the files in lib/rest/static/decorated match
#   the files in lib/rest/static/dereferenced. Checks that the decorated
#   schemas in lib/rest/static/decorated are not in development mode.
#   Development mode schemas have a branch name and development mode tag in the
#   info.version property.
# **Why we have it**: To ensure that we aren't every shipping decorated schemas
#   that are out of sync with the source derefereced schema. To ensure that
#   decorated schemas generated locally are not published. Locally generated
#   decorated schemas are pushing up to the remote for staging purposes only.
# **Who does it impact**: Docs content writers updating REST API docs and
#   the docs engineering team as maintainers of the scripts and workflows.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'lib/rest/static/**'
      - 'script/rest/**/*.js'
      - 'package*.json'

jobs:
  check-schema-versions:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup node
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Differences between decorated and dereferenced files indicates a problem
      - name: Generate decorated files to check that there are no differences
        run: script/rest/update-files.js --decorate-only

      - name: Check if deref/decorated schemas are dev mode and that they match
        run: .github/actions-scripts/openapi-schema-branch.js
