name: Pa11y

# **What it does**: Runs a static accessibility check on high traffic docs pages.
# **Why we have it**: We want accessibility support for the docs.
# **Who does it impact**: Docs engineering, users who need accessibility features.

on:
  workflow_dispatch:
  schedule:
    - cron: '25 17 * * *' # once a day at 17:25 UTC / 11:50 PST
jobs:
  test:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Run build scripts
        run: npm run build

      - name: Run pa11y tests
        run: npm run pa11y-test
