# NOTE: Changes to this file should also be applied to './test.yml'

name: Node.js Tests - Windows

# **What it does**: This runs our tests on Windows.
# **Why we have it**: We want to support Windows contributors to docs.
# **Who does it impact**: Anyone working on docs on a Windows device.

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '50 19 * * *' # once a day at 19:50 UTC / 11:50 PST

env:
  CI: true

jobs:
  test:
    runs-on: windows-latest
    if: (github.event_name != 'pull_request') || (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'Windows') || contains(github.event.pull_request.labels.*.name, 'windows')))
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test-group:
          [
            content,
            graphql,
            meta,
            rendering,
            routing,
            unit,
            linting,
            translations,
          ]
    steps:
      - name: Check out repo
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
        with:
          # Enables cloning the Early Access repo later with the relevant PAT
          persist-credentials: 'false'

      - name: Setup node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - if: ${{ github.repository == 'github/docs-internal' }}
        name: Clone early access
        run: npm run heroku-postbuild
        env:
          DOCUBOT_REPO_PAT: ${{ secrets.DOCUBOT_REPO_PAT }}
          GIT_BRANCH: ${{ github.head_ref || github.ref }}

      - if: ${{ github.repository != 'github/docs-internal' }}
        name: Run build script
        run: npm run build

      - name: Run tests
        run: npm run test tests/${{ matrix.test-group }}/
